"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, type ReactNode } from "react";
import { Activity, BarChart3, Bell, Boxes, Car, Contact, LayoutDashboard, LogOut, Map, Package, Settings, ShieldCheck, Truck } from "lucide-react";
import { cn } from "@/lib/utils";
import { useAuth } from "./auth-provider";
import { Logo } from "./logo";
import { ThemeToggle } from "./theme-toggle";
import { Button } from "./ui/button";
const items=[{href:"/dashboard",label:"Overview",icon:LayoutDashboard},{href:"/deliveries",label:"Deliveries",icon:Package},{href:"/customers",label:"Customers",icon:Contact},{href:"/drivers",label:"Drivers",icon:Truck},{href:"/vehicles",label:"Vehicles",icon:Car},{href:"/routes",label:"Routes",icon:Map},{href:"/reports",label:"Reports",icon:BarChart3},{href:"/notifications",label:"Notifications",icon:Bell},{href:"/profile",label:"Profile",icon:Settings}];
export function DashboardShell({children}:{children:ReactNode}){const path=usePathname();const router=useRouter();const {user,loading,logout}=useAuth();useEffect(()=>{if(!loading&&!user)router.replace("/login")},[loading,user,router]);if(loading||!user)return <div className="grid min-h-screen place-items-center"><div className="size-10 animate-spin rounded-full border-4 border-zinc-200 border-t-emerald-600"/></div>;return <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900 lg:block"><Logo/><nav className="mt-8 space-y-1">{items.map(({href,label,icon:Icon})=><Link key={href} href={href} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800",path===href&&"bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300")}><Icon size={18}/>{label}</Link>)}{user.role==="ADMIN"&&<><Link href="/admin/users" className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium",path==="/admin/users"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300":"text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800")}><ShieldCheck size={18}/>Administration</Link><Link href="/admin/system" className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium",path==="/admin/system"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300":"text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800")}><Activity size={18}/>System monitoring</Link></>}</nav><div className="absolute bottom-4 left-4 right-4 rounded-xl border border-zinc-200 p-3 dark:border-zinc-700"><p className="truncate text-sm font-semibold">{user.firstName} {user.lastName}</p><p className="truncate text-xs text-zinc-500">{user.email}</p><Button variant="ghost" size="sm" className="mt-2 w-full justify-start" onClick={async()=>{await logout();router.push("/")}}><LogOut size={16}/>Sign out</Button></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-zinc-200 bg-white/90 px-4 backdrop-blur dark:border-zinc-800 dark:bg-zinc-900/90 sm:px-6"><div className="lg:hidden"><Logo/></div><div className="hidden items-center gap-2 text-sm text-zinc-500 lg:flex"><Boxes size={16}/>Operations workspace</div><ThemeToggle/></header><main className="p-4 sm:p-6 lg:p-8">{children}</main><nav className="fixed inset-x-0 bottom-0 z-30 flex justify-around border-t border-zinc-200 bg-white p-2 dark:border-zinc-800 dark:bg-zinc-900 lg:hidden">{items.slice(0,5).map(({href,label,icon:Icon})=><Link key={href} href={href} className={cn("flex flex-col items-center gap-1 rounded-lg px-2 py-1 text-[10px] text-zinc-500",path===href&&"text-emerald-600")}><Icon size={18}/>{label}</Link>)}</nav></div></div>}
