"use client";
import { useQuery } from "@tanstack/react-query";
import { Car, Contact, Package, Truck } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, apiMessage } from "@/lib/api";
import type { DashboardSummary } from "@/lib/types";
import { formatDate, titleCase } from "@/lib/utils";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
export default function Dashboard(){const query=useQuery({queryKey:["dashboard"],queryFn:async()=>{const {data}=await api.get<{data:DashboardSummary}>("/dashboard/summary");return data.data}});if(query.isLoading)return <p>Loading dashboard…</p>;if(query.isError)return <p className="text-red-600">{apiMessage(query.error)}</p>;const data=query.data!;const metrics=[["Deliveries",data.totals.deliveries,Package],["Drivers",data.totals.drivers,Truck],["Vehicles",data.totals.vehicles,Car],["Customers",data.totals.customers,Contact]] as const;const chart=Object.entries(data.status).map(([name,value])=>({name:titleCase(name),value}));return <><PageHeader title="Operations overview" description="Live delivery, fleet and customer activity across RouteWell."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon])=><Card key={label}><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 text-3xl font-bold">{value.toLocaleString()}</p></div><span className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"><Icon size={21}/></span></CardContent></Card>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card><CardHeader><h2 className="font-semibold">Delivery status</h2><p className="text-sm text-zinc-500">Current workload by operational stage.</p></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#059669" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><h2 className="font-semibold">Recent deliveries</h2><p className="text-sm text-zinc-500">Latest records created in the system.</p></CardHeader><CardContent className="space-y-3">{data.recent.map(item=><div key={item.id} className="flex items-center justify-between rounded-xl border border-zinc-100 p-3 dark:border-zinc-800"><div className="min-w-0"><p className="truncate text-sm font-medium">{item.trackingNumber}</p><p className="truncate text-xs text-zinc-500">{item.customer.name} · {formatDate(item.scheduledAt)}</p></div><Badge value={item.status}/></div>)}</CardContent></Card></div></>}
